export type ManagementItems = {
  id: number,
  itemDesc: string,
  itemText: string,
};

const managementItems: ManagementItems[] = [
  {
    id: 1,
    itemDesc: "Employee Performance Analysis",
    itemText:
      "With DueFocus, you can track time and analyze every team's workflow. Our Team Pulse interface allows recording all the activities in real-time mode. Thus, your employees can also access the statistics of their performance, compete with colleagues, plan tasks, and establish communications.",
  },
  {
    id: 2,
    itemDesc: "Advanced Reporting",
    itemText:
      "Simplify the process of creating and analyzing your employee's reports. DueFocus time tracking software provides a clear view of the team's KPI and workflow.",
  },
  {
    id: 3,
    itemDesc: "Invoice Payment Function",
    itemText:
      "Directly in the time tracking application, you have the opportunity to expose the invoice to the customer not only based on the data generated by your team but also with manual invoices.",
  },
  {
    id: 4,
    itemDesc: "Time Management As a Habit",
    itemText:
      "Using DueFocus is not just about tracking time spent on tasks. It's about developing a habit of time management, thereby increasing efficiency and boosting incomes.",
  },
];

export default managementItems;
